spring.application.name=RentCar-dev
server.port=9080

#Spring JPA
#Se realiza la conección
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/RentCar_bd?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root.12345

#Creación de las tablas
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true