spring.application.name=RentCar-dev
server.port=9080

# conexi�n MySQL
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/RentCar_bd?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root.12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=zQr9PDUWOOnJJj8NU8fG04TGIqoOg1i9Gs3fVDWVtRO
jwt.expiration=86400000


