spring.application.name=RentCar-prod

# Perfil activo
spring.profiles.active=dev

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# usuario de seguridad
spring.security.user.name=admin
spring.security.user.password=admin123